### ISSUE TITLE
version 0.4.0 sorts in place by default?

### ISSUE THREAD

**Issue by gerases** [mcrossen/deepsort#4]
Ruby 1.8.7

```
#!/usr/bin/ruby

require 'pp'
require 'rubygems'
require 'deepsort'

nested = {"z" => 4, "b" => 3, "a"=>[2, 1] }
nested.deep_sort
pp nested # sorts in place without the `!`?

nested = {"z" => 4, "b" => 3, "a"=>[2, 1] }
pp nested.deep_sort # prints the original array
```

Result:
```
{"a"=>[2, 1], "b"=>3, "z"=>4}
{"z"=>4, "b"=>3, "a"=>[1, 2]}
```

**Comment by mcrossen** [comment]
@gerases thanks for your feedback!

tl;dr - this issue seems specific for ruby 1.8.7; use a newer version if you can. I ran the same code on ruby 2.3.4 without issue.

While debugging this, I did find some interesting tidbits. For instance, you could remove the first `nested.deep_sort` in your code and it doesn't change the output. To me, this implies that something strange goes on in ruby 1.8.7 with regards to hash literals or sorting the underlying data structure. Its no surprise that attempting to sort it will produce strange results. I'll update the gemspec to require ruby versions greater than 1.8.7
